# Generated by Django 5.1.7 on 2025-04-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('R_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_percentage', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_assessment.user')),
            ],
        ),
    ]
