# Generated by Django 5.1.7 on 2025-03-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('A_id', models.AutoField(primary_key=True, serialize=False)),
                ('A_name', models.CharField(max_length=255)),
                ('A_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='E_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
