# Generated by Django 5.1.5 on 2025-04-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_assessment', '0003_policydocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyDocument',
        ),
    ]
