# Generated by Django 5.1.5 on 2025-04-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_assessment', '0004_delete_policydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
